sudo: false
env:
  global:
    - NODE_ENV=development
language: node_js
node_js:
  - '10.15.1'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coveralls
